// ----------------------------------------------------------------------------
// bridge_68k_pal.v — Compact 68000 bridge using one 22V10 PAL/GAL.
//
// Same behaviour as bridge_68k.v (the pure-74-series build), but with all
// of the FSM, /AS synchroniser, /DTACK generation, strobe gating, and
// output-enable logic absorbed into a single 22V10.  The 74LS245s and
// 74LS244s remain as physical chips (not enough I/O on a 22V10 to drive
// 23 address bits + 16 data bits).
//
//                              BOM: 6 chips
//   U1  74LS244   (address A[8:1] buffer)
//   U2  74LS244   (address A[16:9] buffer)
//   U3  74LS244   (address A[23:17] buffer)
//   U4  74LS245   (D[15:8] ↔ DATA[7:0]; cross-wired UDS lane)
//   U5  74LS245   (D[7:0]  ↔ DATA[15:8]; cross-wired LDS lane)
//   U6  22V10     (FSM + sync + /DTACK + strobes + 245 OEs)
//
// Compared with the pure-74 build (12 chips), the PAL absorbs U6-U12:
// the two 74LS74 dual flip-flops, both 74LS00 NAND quads, both 74LS08
// AND quads, and the 74LS32 OR quad.
//
// 22V10 macrocell allocation (10 of 10 used — exact fit):
//   M1  as_n_sync0   registered  (D = cpu_as_n,        clk = bus_clk)
//   M2  as_n_sync1   registered  (D = as_n_sync0,      clk = bus_clk)
//   M3  S0           registered  (D = S0_next,         clk = bus_clk)
//   M4  S1           registered  (D = S1_next,         clk = bus_clk)
//   M5  cpu_dtack_n  combinational  (= ~(S1 & S0))
//   M6  bus_wstrb_0  combinational  (= active & ~cpu_rw & ~cpu_uds_n)
//   M7  bus_wstrb_1  combinational  (= active & ~cpu_rw & ~cpu_lds_n)
//   M8  bus_rstrb    combinational  (= cycle_active & cpu_rw & (~uds_n | ~lds_n))
//   M9  u4_oe_n      combinational  (= ~(cycle_active & ~cpu_uds_n))
//   M10 u5_oe_n      combinational  (= ~(cycle_active & ~cpu_lds_n))
//
// Note: the 68000's /IPL[2:0] interrupt input is generated by the
// host-side interrupt controller (see backplane.md), not by the bridge.
// That separation is what keeps the bridge fitting in a single 22V10.
// ----------------------------------------------------------------------------
`default_nettype none

module pal_22v10_68k (
    input  wire bus_clk,
    input  wire bus_reset_n,
    input  wire cpu_as_n,
    input  wire cpu_uds_n,
    input  wire cpu_lds_n,
    input  wire cpu_rw,
    input  wire bus_ready,
    output wire cpu_dtack_n,
    output wire bus_wstrb_0,
    output wire bus_wstrb_1,
    output wire bus_rstrb,
    output wire u4_oe_n,
    output wire u5_oe_n,
    output wire oe_n_addr     // address-buffer OE (shared U1/U2/U3); reuses one of the spare bits
);
    // Registered macrocells
    reg as_n_sync0 = 1'b1;   // /AS idle is high
    reg as_n_sync1 = 1'b1;
    reg S0         = 1'b0;
    reg S1         = 1'b0;

    wire as_active = ~as_n_sync1;     // /AS low after sync

    // State machine: IDLE (00) → ACTIVE (01) → DONE (11) → IDLE
    wire S1_next = ( ~S1 &  S0 & bus_ready)        // ACTIVE + ready  → DONE
                 | (  S1 &  S0 & as_active);        // DONE + /AS low  → stay
    wire S0_next = ( ~S1 & ~S0 & as_active)         // IDLE  + /AS low → ACTIVE
                 | ( ~S1 &  S0 & as_active)         // ACTIVE while /AS low: hold
                 | (  S1 &  S0 & as_active);        // DONE while /AS low: hold

    always @(posedge bus_clk or negedge bus_reset_n) begin
        if (!bus_reset_n) begin
            as_n_sync0 <= 1'b1;
            as_n_sync1 <= 1'b1;
            S0         <= 1'b0;
            S1         <= 1'b0;
        end else begin
            as_n_sync0 <= cpu_as_n;
            as_n_sync1 <= as_n_sync0;
            S0         <= S0_next;
            S1         <= S1_next;
        end
    end

    wire cycle_active = S0;            // ACTIVE or DONE
    wire in_active    = S0 & ~S1;      // ACTIVE only (writes strobe here, not in DONE)
    wire in_done      = S0 &  S1;

    // Combinational outputs
    assign cpu_dtack_n = ~in_done;
    assign bus_wstrb_0 = in_active & ~cpu_rw & ~cpu_uds_n;
    assign bus_wstrb_1 = in_active & ~cpu_rw & ~cpu_lds_n;
    assign bus_rstrb   = cycle_active & cpu_rw & (~cpu_uds_n | ~cpu_lds_n);
    assign u4_oe_n     = ~(cycle_active & ~cpu_uds_n);
    assign u5_oe_n     = ~(cycle_active & ~cpu_lds_n);

    // Address-buffer OE shares the cycle_active signal — drive only while
    // the bridge owns the bus.
    assign oe_n_addr   = ~cycle_active;
endmodule


// Top-level bridge: 1 PAL + 3 LS244 + 2 LS245 = 6 chips.
//
// Note on /IPL[2:0]: the per-slot interrupt aggregation now lives in the
// host-side interrupt controller (see bus-design/docs/backplane.md), so
// the bridge has no IRQ inputs/outputs.  This is what makes 6 chips a
// hard floor — the bus, the buffers, and one PAL.
module bridge_68k_pal (
    // 68000 side
    input  wire        cpu_as_n,
    input  wire        cpu_uds_n,
    input  wire        cpu_lds_n,
    input  wire        cpu_rw,
    input  wire [22:0] cpu_addr,
    inout  wire [15:0] cpu_data,
    output wire        cpu_dtack_n,

    // Bus side
    input  wire        bus_clk,
    input  wire        bus_reset_n,
    output wire [23:0] bus_addr,
    output wire [3:0]  bus_wstrb,
    output wire        bus_rstrb,
    inout  wire [31:0] bus_data,
    input  wire        bus_ready
);
    wire oe_n_addr;
    wire u4_oe_n, u5_oe_n;
    wire bus_wstrb_0, bus_wstrb_1;

    // U6 — single 22V10 PAL/GAL.
    pal_22v10_68k U6 (
        .bus_clk     (bus_clk),
        .bus_reset_n (bus_reset_n),
        .cpu_as_n    (cpu_as_n),
        .cpu_uds_n   (cpu_uds_n),
        .cpu_lds_n   (cpu_lds_n),
        .cpu_rw      (cpu_rw),
        .bus_ready   (bus_ready),
        .cpu_dtack_n (cpu_dtack_n),
        .bus_wstrb_0 (bus_wstrb_0),
        .bus_wstrb_1 (bus_wstrb_1),
        .bus_rstrb   (bus_rstrb),
        .u4_oe_n     (u4_oe_n),
        .u5_oe_n     (u5_oe_n),
        .oe_n_addr   (oe_n_addr)
    );

    // Address buffers — U1, U2, U3 (74LS244 each).
    SN74LS244 U1 (
        .OE1_n(oe_n_addr), .A1(cpu_addr[3:0]),  .Y1(bus_addr[4:1]),
        .OE2_n(oe_n_addr), .A2(cpu_addr[7:4]),  .Y2(bus_addr[8:5])
    );

    SN74LS244 U2 (
        .OE1_n(oe_n_addr), .A1(cpu_addr[11:8]),  .Y1(bus_addr[12:9]),
        .OE2_n(oe_n_addr), .A2(cpu_addr[15:12]), .Y2(bus_addr[16:13])
    );

    // Bank 2's four outputs cover bus_addr[23:21] with one line dangled.
    // (See bridge_68k.v for the full story — earlier sketches wrote
    // bus_addr[23:20] which double-drove bus_addr[20].)
    wire u3_y2_lsb_unused;
    SN74LS244 U3 (
        .OE1_n(oe_n_addr), .A1(cpu_addr[19:16]),         .Y1(bus_addr[20:17]),
        .OE2_n(oe_n_addr), .A2({cpu_addr[22:20], 1'b0}), .Y2({bus_addr[23:21], u3_y2_lsb_unused})
    );

    assign bus_addr[0] = 1'b0;

    // Data transceivers — U4, U5 (74LS245 each, cross-wired).
    SN74LS245 U4 (
        .DIR(~cpu_rw), .OE_n(u4_oe_n),
        .A(cpu_data[15:8]), .B(bus_data[7:0])
    );

    SN74LS245 U5 (
        .DIR(~cpu_rw), .OE_n(u5_oe_n),
        .A(cpu_data[7:0]),  .B(bus_data[15:8])
    );

    assign bus_data[31:16] = {16{1'bz}};

    // WSTRB layout
    assign bus_wstrb[0]   = bus_wstrb_0;
    assign bus_wstrb[1]   = bus_wstrb_1;
    assign bus_wstrb[3:2] = 2'b00;
endmodule

`default_nettype wire
